sudo: required
services:
  - docker

language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - docker version
  - docker info

script:
  - mvn clean verify -f alma-server/pom.xml -e

after_failure:
  - cat /var/log/docker.log
  - sudo cat /var/log/upstart/docker.log
